version: "3.8"
services:
  spark-master:
    image: bitnami/spark:3.4.1
    ports:
      - "7077:7077" # spark master port
      - "8081:8080" # <-- expose the Master web UI
      # - "8081:8081"  # optional: if you ever want the worker UI
    networks:
      - streaming_net
  spark-worker:
    image: bitnami/spark:3.4.1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
    depends_on:
      - spark-master
    networks:
      - streaming_net

networks:
  streaming_net:
    external: true
