version: '3.8'
services:
  spark-master:
    image: bitnami/spark:3.4.1
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - streaming_net

  spark-worker:
    image: bitnami/spark:3.4.1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
    depends_on:
      - spark-master
    networks:
      - streaming_net

networks:
  streaming_net:
    external: true
