version: "3"
services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENER=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    networks:
      - spark-net

  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_LISTENER_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
