version: "3.8"

services:
  airflow-webserver:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
    ports:
      - "8083:8080"
    command: webserver
    networks:
      - orchestration_spark-net

  airflow-scheduler:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
    command: scheduler
    networks:
      - spark-net
      - streaming_net

  airflow-worker:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
    command: worker
    networks:
      - spark-net
      - streaming_net

  airflow-init:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
    command: db init
    networks:
      - spark-net
      - streaming_net

  airflow-flowers:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
    command: celery flower
    ports:
      - "5555:5555"
    networks:
      - spark-net
      - streaming_net

volumes:
  airflow_data:

networks:
  spark-net:
    driver: bridge
  streaming_net:
    driver: bridge
