version: '3.8'
services:
  airflow-webserver:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
    command: worker

volumes:
  airflow_data:
